Post.create(:id => 7, :title => "asdasdasdadinaossaopdfnoasbouasbfoubsafoupbsaofbsdauofb", :description => "dabdad", :consumer_id => 2, :price => 40, :categories => ["general"])
Post.create(:id => 6, :title => "adasd", :description => "asdasd", :consumer_id => 2, :price => 40, :categories => ["beauty"])
Post.create(:id => 5, :title => "car wash ", :description => "aspdimadimasdm", :picture => "images.jpg", :consumer_id => 1, :price => 10, :categories => ["automobile"], :provider_id => 2)
Post.create(:id => 4, :title => "asdasd", :description => "asdasd", :picture => "images.jpg", :consumer_id => 1, :price => 25, :categories => ["creative"], :provider_id => 2)
Post.create(:id => 3, :title => "asdas", :description => "asdasd", :picture => "images.jpg", :consumer_id => 1, :price => 50, :categories => ["computer"], :provider_id => 3)
Post.create(:id => 2, :title => "ads", :description => "asdasdads", :consumer_id => 1, :price => 25, :categories => ["general"])
Post.create(:id => 1, :title => "asd", :description => "asdasd", :consumer_id => 1, :price => 50, :categories => ["computer"], :provider_id => 2)
