language: ruby
rvm:
  - "1.9.3"
  - "2.2.1"
  - "2.1.5"
  - jruby-18mode # JRuby in 1.8 mode
  - jruby-19mode # JRuby in 1.9 mode
  - rbx
env:
  - DB=mysql
script:
  - RAILS_ENV=travis bundle exec rake db:migrate --trace
  - RAILS_ENV=travis bundle exec rake db:test:prepare
  - RAILS_ENV=travis bundle exec rake
before_script:
  - mysql -e 'create database library_test'
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
